# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-EvalContext
version:      0.05
version_from: Devel/EvalContext.pm
installdirs:  site
requires:
    Data::Alias:                   1.01
    PadWalker:                     1
    YAML:                          0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
